name: CobbleDialogNpc
version: '1.0'
main: com.example.cobbledialognpc.CobbleDialogNpc
api-version: '1.21'
authors: [ XiaoCaoAwA ]

commands:
  cdn:
    description: CobbleDialogNPC 主命令
    usage: /cdn <subcommand>
    aliases: [cobbledialognpc, cdnpc]
    permission: cobbledialognpc.command.use
    permission-message: "§c你没有权限使用此命令！"

permissions:
  cobbledialognpc.command.use:
    description: 允许使用 CobbleDialogNPC 基础命令
    default: true
  cobbledialognpc.command.open:
    description: 允许使用打开对话配置文件命令
    default: op